---
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(CoordinateCleaner)
library(countrycode)
library(gganimate)

nobel_winners_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv")

###Transforming 'Pre WW1-WW2' countries to 'Post WW1-WW2' countries
nobel_winners_processed <- nobel_winners_raw %>%
   mutate(birth_country = str_replace(birth_country,".*\\(", ""),
         birth_country = str_replace(birth_country,"\\)$",""),
         death_country = str_replace(death_country,".*\\(", ""),
         death_country = str_replace(death_country,"\\)$",""),
         age_won = prize_year - year(birth_date),
         decade = prize_year - (prize_year %% 10))

```
```{r}
###Getting centroids from countryref (needs CoordinateCleaner package)
###Renaming a couple of countries to match original data country name
centriods <- countryref %>%
  select(name,centroid.lon,centroid.lat,countrycode = iso3)%>%
  distinct(name, .keep_all = TRUE)%>%
  rename("birth_country" = name)%>%
  filter(!is.na(centroid.lon),!is.na(centroid.lat))%>%
  tbl_df()%>%
  mutate(birth_country = fct_recode(birth_country,
    "United States of America" = "United States",
    "Czech Republic" = "Czechia",
    "Bosnia and Herzegovina" = "Bosnia & Herzegovina",
    "East Timor" = "Timor-Leste",
    "Saint Lucia" = "St. Lucia",
    "Myanmar" = "Myanmar (Burma)",
    "People's Republic of China" = "China",
    "Republic of Macedonia" = "Macedonia",
    "Trinidad" = "Trinidad & Tobago"
))

tes <- nobel_winners_geo%>%
  count(birth_country,sort =TRUE)
tes2<- nobel_winners_processed %>%
  count(birth_country,sort = TRUE)

right_join(tes,tes2,by = "birth_country")### Check misspelled countries between datasets

world <- map_data("world")%>%
  rename("birth_country" = region)%>%
  left_join(centriods)

 
nobel_winners_geo <- nobel_winners_processed %>%
  inner_join(centriods, by = "birth_country")%>%
  filter(!is.na(centroid.lon),!is.na(centroid.lat))%>%
  select(prize_year,birth_country,decade,countrycode,centroid.lon,centroid.lat)

cumsum_geo <- nobel_winners_geo %>%
  select(decade,birth_country,centroid.lon,centroid.lat)%>%
  complete(decade,birth_country)%>%
  group_by(decade,birth_country,centroid.lon,centroid.lat)%>%
  summarize(x = n())%>%
  ungroup()%>%
  group_by(birth_country)%>%
  mutate(decade = paste0(decade,"-",decade+9),
         value = ifelse(!is.na(centroid.lat),x,0),
         cumsum = as.integer(cumsum(value)),
         centroid.lon1 = centroid.lon,
         centroid.lat1 = centroid.lat)%>%
  fill(centroid.lat1,birth_country,.direction = "up")%>%
  fill(centroid.lat1,birth_country,.direction = "down")%>%
  fill(centroid.lon1,birth_country,.direction = "up")%>%
  fill(centroid.lon1,birth_country,.direction = "down")


  p <- ggplot(world)+
  geom_polygon(aes(x = long,y= lat,group = group),fill="orange",size = 1, color = "white")+
  geom_text(data = cumsum_geo,aes(x=centroid.lon1,y=centroid.lat1,label = round(cumsum)),size = 6)+
  borders("world")+
  coord_map(xlim=c(-180,180), ylim=c(-60, 90))+
  labs(x="",
       y="")+
  theme_void()+
    theme(plot.title = element_text(hjust = 0.5, vjust = 0.05, size=25)) +
    theme(plot.subtitle = element_text(hjust = 0.5, vjust = 0.05,size=15))
    

anim <- p +
  transition_states(decade,
                    transition_length = 2,
                    state_length = 2)+
   ggtitle('Nobel prize winners from the 20th centrury to present by country of birth',
     subtitle = 'Current decade: {closest_state}')


anim_save("nobel3.gif", anim, width = 1920, height = 1080)
```






