---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(scales)
library(lubridate)
library(USAboundaries)
library(ggthemes)
library(gganimate)
theme_set(theme_light())
```

```{r}
drought <- tidytuesdayR::tt_load('2021-07-20')

drought_set <- drought$drought
```

```{r}
usmap <- map_data("state")%>%
  rename(state_name = region)%>%
  mutate(state_name = str_to_title(state_name))%>%
  inner_join(state_codes, by = "state_name")


drought_summarized <- drought_set%>%
  group_by(state_abb,year = year(valid_start))%>%
  summarize(avg_drought = mean(area_pct))%>%
  ungroup()

drought_map <- drought_summarized%>%
  rename(state_abbr = state_abb)%>%
  inner_join(usmap)


```


```{r}
p <- drought_map%>%
  ggplot(aes(long,lat,group = group,fill = avg_drought))+
  geom_polygon(color = "white")+
  scale_fill_gradient2(low = "steelblue",high = "red",midpoint = 40)+
  theme_map()+
  theme(legend.position = "none",plot.title = element_text(size = 15,family="serif"),plot.subtitle = element_text(size = 12,family="serif"),plot.caption = element_text(size = 10,family="serif"))+
  coord_map()+
  labs(title= "Driest states in the past two decades",
       subtitle = 'Year: {round(frame_time,0)}',
       caption = "Source: US Drought Monitor") +
  transition_time(year) +
  ease_aes('linear')


#anim <- animate(p,nframes =130,fps = 60,end_pause = 5)
#anim_save("your_path.gif",anim)
```

